apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources-generated/${CLUSTER_ENV}/${CLUSTER_NAME}

sortOptions:
  order: legacy
  legacySortOptions:
    orderFirst:
      - Namespace
      - OCIRepository
      - Kustomization
    orderLast:
      - SecretStore
      - Gateway
