apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${APPLICATION_NAMESPACE}-splunk-efs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: ${SPLUNK_EFS_ID}::${SPLUNK_ACCESS_POINT_ID}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${APPLICATION_NAMESPACE}-data-efs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: ${DATA_EFS_ID}::${DATA_ACCESS_POINT_ID}
