apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: ${APPLICATION_NAME}
  namespace: ${APPLICATION_NAMESPACE}
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: ${APPLICATION_NAMESPACE}-external-secret
