apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${APPLICATION_NAMESPACE}-external-secret
  namespace: ${APPLICATION_NAMESPACE}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/EKS_${CLUSTER_ENV}_${CLUSTER_NAME}_${APPLICATION_NAMESPACE}_externalSecrets_role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${APPLICATION_NAMESPACE}
  namespace: ${APPLICATION_NAMESPACE}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/EKS_${CLUSTER_ENV}_${CLUSTER_NAME}_${APPLICATION_NAMESPACE}_pod_role
